### ISSUE TITLE
Random suggestions for the plugin

### ISSUE THREAD

**Issue by balta2ar** [mg979/vim-visual-multi#2] opened 2018-05-21 10:50 UTC
1. It's good that there is detailed wiki, but overall it's a bit frightening and complicated. I wish there were a quick start tutorial that would show how to do simple things first. Besides, not all GIFs show the keys pressed.
2. I'm using neovim and "Info line" prompts me to press a key everytime, which is a bit annoying:
```
 M+ / v- / b- / o-  [2]  Switched to Cursor Mode. 3 cursors.   Current patterns: ['self']
Press ENTER or type command to continue
```

**Comment by mg979** [comment] 2018-05-21 10:56
1. I'll add a quick start

2. this is a bit of a problem, it doesn't depend on neovim. I had the same problem while testing it on a laptop, but it doesn't happen on my desktop PC. It may be the screen resolution, I don't know. It can be solved by increasing `cmdheight`, is yours at least 2? I could increase it while VM is active, then revert it, but it's not an optimal solution.

**Comment by balta2ar** [comment] 2018-05-21 11:03
> solved by increasing cmdheight, is yours at least 2

It was 1, setting to 2 helped, but that's a bit of a waste of the vertical space on my screen. I'd prefer to set it to 1... Do you think this line could be integrated with vim-airline (vim-powerline)? Many plugins  do that.

**Comment by mg979** [comment] 2018-05-21 11:07
I also use airline and it should be possible to integrate it, having colors would be difficult but maybe possible. What I can do for now, is to set temporarily `cmdheight` to 2 when VM starts, then restore the old value. Or an option to disable/reduce the line, I'll make some tests with cmdheight=1 and see how it looks.

**Comment by balta2ar** [comment] 2018-05-21 13:33
In my colorscheme, I can barely see cursors... How do I set custom colors for different modes?

**Comment by mg979** [comment] 2018-05-21 21:54
Sorry for the late answer (was afk). You can define the different highlights:

```
    let g:VM_Selection_hl     = 'Visual'
    let g:VM_Mono_Cursor_hl   = 'DiffChange'
    let g:VM_Ins_Mode_hl      = 'Pmenu'
    let g:VM_Normal_Cursor_hl = 'DiffAdd'
```

These way the highlight will be the same for all schemes. You can have scheme-specific highlight but it's more complicated. I'll add in the wiki some examples for different color schemes.

**Comment by balta2ar** [comment] 2018-05-22 08:33
Thank you! As for `Ctrl-d`, I expected it to select using word boundaries. Consider this code:
```python
    def submit(self, data, f, *args, **kwargs):
        result = f(*args, **kwargs)
        self._futures.append(CustomFuture(result))
        self._data.append(data)
```
I'd like to select `data` but skip `_data` automatically. Is it possible?

Also, it looks like the plugin is turning off my `hls` setting. I have to turn on `set hls` manually.

**Comment by mg979** [comment] 2018-05-22 09:16
C-d by default works like that (no word boundaries but you can either:

* press C-d, then C-w: it will convert the last pattern to use word boundaries
* if you activated [__*g:VM_s_mappings*__](https://github.com/mg979/vim-visual-multi/wiki/3.-Regions-and-patterns), you can use `s}`
* use `*`, but it only works after VM has started (`gr` starts VM empty)

About hls, right now it's turned off after exit, yes. I'll add a check so that it just restores the old value.

**Comment by balta2ar** [comment] 2018-05-22 09:27
Thanks! Could you please put this into quick start? That's a very common usage pattern, I think, and it's default behaviour in vim-mulpitle-cursors.

By the way, I noticed that upon `Ctrl-d` is takes not the current word, but `+` register. Could you please check?

Another frequent pattern for me is this:
1. Find something using `/` or find next current word using `*`.
2. Create Visual selection (usually Line selection).
3. Convert entries that match search register into cursors but only within the selection.

Is that currently possible?

**Comment by mg979** [comment] 2018-05-22 09:43
> By the way, I noticed that upon Ctrl-d is takes not the current word, but + register

This sounds strange, I'll check, but to me, it selects the word. What clipboard setting are you using?

You can start regex search with `g/`, it will select the first occurrence, then you can use C-d to find next, C-s to skip.

After start, there are alternatives to C-d:
* `[`, `]` find next/previous
* `q` skips, `Q` removes

I generally use `s]` to start, then `]` or `[` to find next/previous.

About 3., it's not possible but it's a good idea (like find all within range, right?).

**Comment by balta2ar** [comment] 2018-05-22 09:46
> What clipboard setting are you using?

set clipboard=unnamed,unnamedplus

> like find all within range, right?

Yeah. This is very useful to limit effect within a method, for example.

**Comment by mg979** [comment] 2018-05-22 09:52
> set clipboard=unnamed,unnamedplus

But what is happening, exactly? It doesn't select the word under cursor? It adds the wrong pattern to current search?

I could do it this way: mapping `zs`, and it would work with a motion/text object. For example, `zsap` would find occurrences around the paragraph. Sounds ok?

**Comment by balta2ar** [comment] 2018-05-22 10:20
It uses wrong pattern. I selected and yanked `def submit` then moved to `data` and pressed `Ctrl-d`:
![vm-ctrl-d](https://user-images.githubusercontent.com/340676/40356716-9a4631c0-5dc2-11e8-8c56-7c0745a4e0ac.gif)

So many bindings to remember... Select and find within a selection sounds easier to me, sorry :)

**Comment by mg979** [comment] 2018-05-22 10:33
I can't reproduce the problem using clipboard=unnamed,unnamedplus

![Imgur](https://i.imgur.com/Gmzrcs9.gif)

About the binding, one would be necessary, how would you start it?

**Comment by balta2ar** [comment] 2018-05-22 11:12
> I can't reproduce the problem using clipboard=unnamed,unnamedplus

Could it be specific to neovim?

> About the binding, one would be necessary, how would you start it?

With vim-multiple-cursors plugin I do the following: I select lines and press `Alt-j`:
```vim
nnoremap <silent> <M-j> :MultipleCursorsFind <C-R>/<CR>
vnoremap <silent> <M-j> :MultipleCursorsFind <C-R>/<CR>
```
It's very convenient!

All by bindings for vim-multiple-cursors  are: `Ctrl-n` to find next word/selection, `Ctrl-x` to skip, `Ctrl-p` to go back, `Alt-j` to convert search register to cursors. If this plugin could be a drop-in replacement for basic features it could be just awesome! I understand that you've implemented much more in terms of functionality, but same bindings and same behaviour for basic things could attract new users, I think.

**Comment by mg979** [comment] 2018-05-22 12:20
I could reproduce it in neovim, but only once. I'll keep an eye open on it though.

I'm almost done with that functionality. Right now I set it up like this, but I'll also add it from visual mode using `Alt-j`, reusing current search patterns, so that it matches vim-multiple-cursors behaviour.

#### after C-d:

![Imgur](https://i.imgur.com/6rc4zh9.gif)

#### or after visual mode, with regex (g/):

![Imgur](https://i.imgur.com/lPyW3qH.gif)

**Comment by balta2ar** [comment] 2018-05-22 12:32
> does that work from visual mode or not

Yes is does, that's the point. Cursors are searched for and created only within the visual selection (V-LINE). Without visual selection they are searched for and created in the whole document.

**Comment by mg979** [comment] 2018-05-22 12:34
Ok, I'll keep `Alt+Shift+a` for the whole file and `Alt-j` from visual selection.

**Comment by balta2ar** [comment] 2018-05-22 12:50
Alt-j can do both. Without selection, operate on the whole file. How about that?

**Comment by mg979** [comment] 2018-05-22 13:12
The problem is that `find all` also works from visual mode, and it finds all occurrences of the selected text (also subwords), while in normal mode it looks for whole words, and I'd like to keep that. `Alt-j` right now is used to add cursors vertically, so I can't use that for normal mode either, unless I use `Ctrl-j` to add cursors, as [vis](https://github.com/martanne/vis) does it.

For now I'll set `Alt-j` to work like that in visual mode only. 

Here is the result:

#### if just starting, it uses the search register:

![Imgur](https://i.imgur.com/VqzCZ11.gif)

#### if already started, it uses current patterns:

![Imgur](https://i.imgur.com/hjt5YvM.gif)

**Comment by mg979** [comment] 2018-05-22 13:32
I pushed it in the test branch by the way, now stopping :)

**Comment by balta2ar** [comment] 2018-05-22 16:31
I'm using NVIM v0.2.2, which was released a while ago (but it's still the latest official release). Maybe it's already fixed in HEAD.

**Comment by balta2ar** [comment] 2018-05-23 14:09
Another question: is possible to make `ctrl-d` case sensitive by default?

**Comment by mg979** [comment] 2018-05-23 14:31
The commands don't have an option to set case sensitiveness from the start, right now. You can work around it like this:

```vim
let g:VM_custom_commands = {'Find-Under': ["\<C-d>", ":call VM_Find_under()<cr>"]}

fun! VM_Find_under()
    if !g:VM.is_active
        normal gr
        set nosmartcase
        set noignorecase
    endif
    call vm#commands#find_under(0, 1, 0, 1)
endfun
```

This way your normal setting will be restored when exiting. I'll add an option to set case from the start.

**Comment by mg979** [comment] 2018-05-23 14:39
Btw I pushed that fix for neovim clipboard this morning, and made C-d respect word boundaries by default. I made some more changes (a bit more radical) that I didn't push yet, so if you see something strange happening, I may try to fix them before I go ahead. Thanks for the trying the plugin anyway /).

**Comment by balta2ar** [comment] 2018-05-23 16:30
Thank you! I guess case sensitiveness is less important, so I'll wait for the official option.

I've noticed a little glitch today (it looked like a one-off error) few hours earlier, but now I can't reproduce it and I forgot the exact context when I saw that. If I see it again, I'll report here.

Overall, you did a fantastic job! The fact that it's so much faster and it works with completion menu is just amazing!

**Comment by mg979** [comment] 2018-05-23 23:14
Nice thanks :)

**Comment by balta2ar** [comment] 2018-06-07 09:22
@mg979 Hi! I think I found an edge case. Consider this string:
```
curl -X POST http://localhost:8080/some/url/ -H 'username: testuser1' -H 'userprofile: some_profile' -H 'token: <token>' -H 'Content-Type: application/json' -d '{"data": {"username": "t_admin1", "password": "t_admin1"}}' -k
```
Put cursor on the first "t_admin1" word. Press `ctrl-d` twice, then `c` then type `test`. I get this:
```
t_admin1"}}' -testtestk·
```

**Comment by mg979** [comment] 2018-06-07 13:35
Thanks for reporting. It's a regression from a rather recent [commit](https://github.com/mg979/vim-visual-multi/commit/ee5bb70f355e8241e7655486223fb89665f4cddc), before it worked well. I have to sort it out because it's pretty bad.

**Comment by mg979** [comment] 2018-06-07 14:38
I reverted that change in test branch. Could you please try it? If test branch is ok for now, I'm going to merge it into master because there are a couple of other fixes, thanks.

**Comment by balta2ar** [comment] 2018-06-07 14:46
Yep, now it's working. Thank you!

**Comment by balta2ar** [comment] 2018-06-07 15:01
I've been sitting on the test branch all that time. No other problems so far! Though I've been using only a tiny bit of the functionality, I'm yet to become a power user of this plugin.

**Comment by mg979** [comment] 2018-06-07 15:04
Ok thanks, the important thing is that the most common operations work ok for now.

**Comment by balta2ar** [comment] 2018-06-09 16:07
Hi! Here is another glitch :)

Consider the following text (two columns separated with a single tab):

```
1	abc
2	abc
3	abc
100	abc
200	abc
300	abc
```

I put the cursor on the last word of the last line. Then I press `Alt-k` several times to create cursor upwards. As you can see, one line is skipped:

![](https://i.imgur.com/APyTA2j.png)

I have these settings:
``` vim
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
```

**Comment by balta2ar** [comment] 2018-06-09 16:15
Another one. If I select all `abc`s using Ctrl-D and press `Alt-a` (found on this page https://github.com/mg979/vim-visual-multi/wiki/M.-Most-used-mappings), errors show up. I'm not sure how it should work but I was curious and it exploded:

![](https://i.imgur.com/TedLXhJ.png)

**Comment by mg979** [comment] 2018-06-09 20:04
`Alt-a` is used to align cursors. I don't get any error while using it. Which are the exact keypresses? `C-d`, then `Alt-a` doesn't trigger errors for me.

**Comment by balta2ar** [comment] 2018-06-09 20:42
> The issue with Alt-k is caused by the fact that tabs count as a single column, going up one line is skipped because considered 'shorter'. Columns that are visually aligned can have different column value, when using tabs

I guess vim-multiple-cursors fell for the same trap, which I reported here
https://github.com/terryma/vim-multiple-cursors/issues/260 :)

**Comment by mg979** [comment] 2018-06-09 20:54
About the tab thing, I think I fixed it already, but it could have side effects if a file has mixed indent (basically I'm converting tabs to spaces, then reconvert on exit). It seems to work anyway. Ideal would be to only do that on line with cursors, but it would be difficult to control (for example when removing single cursors in lines with other cursors, or regions spanning several lines, etc). I can include this fix but probably on certain filetypes it could be suboptimal.

About the clipboard thing, it's again a neovim, because using clipboard=unnamed,unnamedplus in vim doesn't give errors with that command. Maybe there is something wrong in the command itself, that can cause the error, I'll check.

**Comment by mg979** [comment] 2018-06-09 21:03
An alternative could be, to only convert tabs on lines for specific commands (adding cursors vertically and alignment being the most obvious).

**Comment by mg979** [comment] 2018-06-09 22:50
I added both possibilities for now:

* adding cursors vertically works by temporarily expanding tabs in the cursor line
* alignment requires a [special setting](https://github.com/mg979/vim-visual-multi/wiki/T.-Troubleshooting#using-tabs), because if done after regions have been created, they should be recalculated and it's frankly a mess I'd like to avoid.

**Comment by balta2ar** [comment] 2018-06-13 21:18
A few more problematic test cases. They all use the following text as a starting point:

```
    test(3, 'III')
    test(4, 'IV')
    test(9, 'IX')
    test(58, 'LVIII')
    test(59, 'LIX')
    test(1994, 'MCMXCIV')
```

## Case 1

Put cursor on number 3 as indicated: `test(|3, 'III')`
Press: `6<A-j>`
Expected: 6 cursors created starting from `3` and straight below
Actual: 6 cursors  are created in the beginning of the lines

## Case 2

Put cursor on number `3` and press `A-j` 6 times to create 6 cursors from `3` and below. The action I want to do is to swap the arguments of the function
Press: `diw` to delete all first arguments, `P` to paste into the same place
Expected: same text as before as we're pasting into the same location. I'd expect each cursor to have it's own independent buffer.
Actual: 1994 is pasted in every location instead

## Configuration:
```
set rtp+=~/.fzf                                                                                                                                                                                
if &compatible                                                                                                                                                                                 
  set nocompatible                                                                                                                                                                             
endif                                                                                                                                                                                          
                                                                                                                                                                                               
call plug#begin('~/.vim/plugged')                                                                                                                                                              
Plug 'mg979/vim-visual-multi'                                                                                                                                                                  
call plug#end()                                                                                                                                                                                
                                                                                                                                                                                               
set clipboard=unnamed,unnamedplus
```
neovim 0.3.0 (finally released few days earlier)

**Comment by mg979** [comment] 2018-06-13 22:04
Huge thanks for keeping updating me of bugs :)

1. yes it's happening (I don't know why), right now A-j doesn't use a proper count (for example it will create 7 cursors if pressing `6<A-j>`, because the first time it creates 2). I will make it use a proper count and also this problem should go away.

2. I'll have to rework delete command (epecially in cursor mode), but I'm not having the problem you describe (with `set clipboard=`)(tested in vim and neovim 0.2.2). It's again the `unnamed,unnamedplus` problem (It's happening with it). The easiest solution for this is to empty clipbloard setting in neovim and restore it on exit, would it be ok?

**Comment by mg979** [comment] 2018-06-13 22:10
The same setting (`unnamed,unnamedplus`) works ok in vim, but not in neovim, so I can't do more than that I think, I don't know what neovim does differently.

**Comment by mg979** [comment] 2018-06-14 03:39
Both issues should be fixed now (in test branch)

**Comment by balta2ar** [comment] 2018-06-14 06:28
Wow, thank you for fixing bugs so quickly!

By the way, behaviour of `P` and `p` is different from the one in vim, is this expected? For example:
```
    test(|1994, 'MCMXCIV')
```
If I press `diwp` in neovim I get this (cursor is over `4`):
```
    test(,199|4 'MCMXCIV')
```
but this plugin gives me this (cursor is over `,`):
```
    test(|,1994 'MCMXCIV')
```

**Comment by balta2ar** [comment] 2018-06-14 11:00
## Case 3

When you leave multiple cursors mode, the primary (original) cursor stays at the position of the last virtual cursor. I'd expect the original cursor to return where it was before. For example, move vim cursor on the first line, create 6 cursors, press `Esc`. You now have a single cursor on the last line. It should be on the first line.

**Comment by balta2ar** [comment] 2018-06-14 11:05
## Case 4

First put cursor on the first line as indicated: `    |test(3, 'III')`
Press: `Alt-j` 6 times to create 6 cursors, `ia` to type `a`, and finally `Esc`.
Actual result:
```
atest(3, 'III')
atest(4, 'IV')
atest(9, 'IX')
atest(58, 'LVIII')
atest(59, 'LIX')
atest(1994, 'MCMXCIV')
```
Spaces (before each `test` word) are gone from the beginning of each line. They are expected to stay.

**Comment by mg979** [comment] 2018-06-14 11:33
1. paste behaviour: right now cursors don't follow pasted content, they stay where they are, not sure if they should do that, many times you'd want to paste stuff in place and keep cursors as they were. But I could address this.

2. vm is actually trying to keep cursor position, reselecting last selected cursor. You can press `{`, `}` to change current cursor, for example `}` would bring you back to the first cursor if you have the last one selected. I can add an option to always reselect first cursor, if it's what you prefer.

3. this seems like a bug but I can't reproduce it. I put spaces or tabs before `test`, press `ia<esc>`, but spaces stay.

**Comment by balta2ar** [comment] 2018-06-14 11:36
@mg979 By the way, have you had a chance to look at any of the testing frameworks for vim plugins? e.g:

* https://github.com/junegunn/vader.vim
* https://github.com/thinca/vim-themis/
* https://github.com/inkarkat/runVimTests

I think the plugin will benefit greatly from using them. I'd be glad to send these problematic cases in pull requests and you will be able to reproduce them instantly and detect regressions before the commit.

**Comment by mg979** [comment] 2018-06-14 11:40
I had a look at vader.vim, it seems the easiest to set up. I didn't get around it yet. I'll try later today.

**Comment by balta2ar** [comment] 2018-06-14 13:29
> not sure if they should do that, many times you'd want to paste stuff in place and keep cursors as they were

actually, me neither, but I saw the difference with regular vim behaviour and decided to report

> I can add an option to always reselect first cursor, if it's what you prefer

Sounds great. It's just how it works in VSCode and Sublime.

> this seems like a bug but I can't reproduce it

Even in neovim with `set clipboard=unnamed,unnamedplus`? I can reproduce it with the minimal vimrc mentioned above.

**Comment by balta2ar** [comment] 2018-06-14 17:05
Originally I found this issue in `ft=python`, but then I was testing on `ft=text`. I added this:
``` vim
let g:VM_no_reindent_filetype = ['text', 'python']
```
and now it works as expected in `ft=text`. However, I found another case in `ft=python`. Using the option above:

## Case 5

Start with the following text (cursor is on the first `test`):
```
def foo():
    |test(3, 'III')
    test(4, 'IV')
    test(9, 'IX')
    test(58, 'LVIII')
    test(59, 'LIX')
    test(1994, 'MCMXCIV')
```
Press: `<A-j>` 6 times, `Ia` to insert `a` in the beginning of each line, then `<Esc><Esc>` to exit cursor mode.
Actual (the first line has extra indentation):
```
def foo():
    a    test(3, 'III')
a    test(4, 'IV')
a    test(9, 'IX')
a    test(58, 'LVIII')
a    test(59, 'LIX')
a    test(1994, 'MCMXCIV')
```
Expected:
```
def foo():
a    test(3, 'III')
a    test(4, 'IV')
a    test(9, 'IX')
a    test(58, 'LVIII')
a    test(59, 'LIX')
a    test(1994, 'MCMXCIV')
```

**Comment by mg979** [comment] 2018-06-14 17:20
The problem is that g:VM_no_reindent_filetype is overridden by g:VM_reindent_filetype (that has 'python' in its defaults), I fixed this (will push now). About case 5, it's normal when reindentation is active (it shouldn't be in your case). Doing `7==` on the `def` line changes nothing.

Unfortunately stopping reindentation is necessary because vim does it by itself and will break the cursors, if you type something that matches `indentkeys`. If you disable autoreindentation for a filetype, then you must reindent the lines by yourself.

**Comment by mg979** [comment] 2018-06-14 17:38
It should be fixed now. I changed [reindentation defaults](https://github.com/mg979/vim-visual-multi/wiki/X.-Customization#automatic-reindentation), so that it's easier to stop it (and `text` is excluded by default).

**Comment by balta2ar** [comment] 2018-06-14 17:52
Thank you very much! Now it works as expected both in text and python with `let g:VM_no_reindent_filetype = ['text', 'python']`. I'll keep it like that for a while and see how it works for me.

**Comment by mg979** [comment] 2018-06-14 18:01
Thanks and sorry for the issue, some default values could be better. I think autoreindentation is going to cause a lot of problems if people don't know it's happening, maybe it would be better to disable by default.

**Comment by balta2ar** [comment] 2018-06-29 08:40
Hi! After recent updates I started seeing this message when I press `Esc` to exit multiple cursor mode:
```
Error detected while processing function vm#reset[11]..218[18]..222:                                                                                                          
line   28:                                                                                                                                                                    
E31: No such mapping                                                                                                                                                          
E31: No such mappingExited Visual-Multi.
```

**Comment by mg979** [comment] 2018-06-29 08:46
Do you have the latest? I don't have this message nor in test or in master.

**Comment by mg979** [comment] 2018-06-29 08:50
Ok I think I found out the problem, I'm fixing it now

**Comment by mg979** [comment] 2018-06-29 08:54
Can you try it now, please? it should be fixed in test branch.

**Comment by balta2ar** [comment] 2018-06-29 08:57
Yes, thank you, it fixed it! Another regression that I noticed is that it started to use either `+` or `*` register again. I'm using your configuration:
```vim
let g:VM_custom_commands = {'Find-Under': ["\<C-d>", ":call vm#commands#find_under(0, 1, 0, 1)<cr>"]}
```
and it looks like `Ctrl-d` now grabs pattern from yank register, i.e. I can't select current word.

**Comment by mg979** [comment] 2018-06-29 09:04
That command isn't necessary anymore. I had removed the line that forced unnamed register for nvim, I thought that clearing the clipboard setting would have been enough, but it's not. I'll restore that line but I'd like to understand better what's happening, because in vim it doesn't happen. I'll amend the previous commit so please do a forced pull (in 5 minutes), thanks.

**Comment by mg979** [comment] 2018-06-29 09:09
Ok it's ready, and thanks for the reports :)

**Comment by balta2ar** [comment] 2018-06-29 09:11
Yay! Works fine, thank you for being so ultra fast! :tada:

**Comment by mg979** [comment] 2018-06-29 09:13
I won't touch that line again without testing it :), sorry for the issue

**Comment by midnio** [comment] 2018-10-12 13:34
Close this issue? @mg979

**Closed** 2019-06-12 19:50 UTC
