### ISSUE TITLE
Reset error with Dracula colorscheme

### ISSUE THREAD

**Issue by sQVe** [mg979/vim-visual-multi#56] opened 2019-04-11 13:05 UTC
Hey!

I've started getting errors when escaping visual multi, i.e. pressing `<Esc>`. I get the following error:

```
Error detected while processing function vm#reset:
line   43:
E492: Not an editor command:                    links to DraculaSearch
Error detected while processing function vm#reset:
line   43:
E492: Not an editor command:                    links to DraculaSearch
```

Pretty confusing. It starts working as soon as I change `colorscheme` or manually set `:VMTheme`.

https://github.com/dracula/vim

**Comment by mg979** [comment] 2019-04-11 13:45
Yes I'm getting the same with Dracula. I'm looking for the cause.

**Comment by mg979** [comment] 2019-04-11 13:52
Ok the problem is that it uses highlight linking, I'm working on a fix.

**Comment by sQVe** [comment] 2019-04-11 13:57
@mg979 As responsive as always. Many thanks. :pray:

**Comment by mg979** [comment] 2019-04-11 14:12
It should be fixed in the test branch. By the way, if you're using deoplete, could you tell me if it's working ok? Because I made changes that should make it work normally (without workarounds such as manual completion with tab). Thanks for reporting

**Comment by sQVe** [comment] 2019-04-11 14:33
@mg979 I actually moved away from deoplete today to coc.nvim. So, I can't test it easily. I'll try it with coc later today though.

**Comment by mg979** [comment] 2019-04-11 14:38
Ok if you don't use it no problem. If you confirm the fix is working I'll merge it into master.

**Comment by sQVe** [comment] 2019-04-11 14:51
@mg979 Works fine with my setup now!

**Closed** 2019-04-11 23:44 UTC
