### ISSUE TITLE
<C-n> does not work properly

### ISSUE THREAD

**Issue by antoinemadec** [mg979/vim-visual-multi#33] opened 2018-12-08 02:47 UTC
With this minimal vimrc:
```
set nocompatible
```

On this file:
```
antoine
madec
antoine
```

Using these commands:
```
<C-n>
<C-n>
C
hello
```

I got:
```
antoine
madec
hello
```

instead of:
```
hello
madec
hello
```

**Comment by mg979** [comment] 2018-12-08 08:38
I can't reproduce this. Vim version?

**Comment by antoinemadec** [comment] 2018-12-08 08:40
Latest from source.

**Comment by mg979** [comment] 2018-12-08 08:44
Ok, I understood the problem, you press `C`, not `c`. Uppercase is used in cursor mode, as in normal mode `C` (same as `c$`), in extend mode (as with `c-n`) you use lowercase `c`, as in visual mode. Still, even `C` shouldn't do that in this case.

By the way you should press lowercase `c` in this case.

**Comment by antoinemadec** [comment] 2018-12-08 08:54
Will try tomorrow. Weird thing is that i think the same commands work with
my own vimrc but not with the minimal vimrc.

**Comment by mg979** [comment] 2018-12-08 09:04
Same here, it doesn't work only with the minimal vimrc, it does work in my main vimrc. When you press `C`, what it does is to change to cursor mode, then do `c$`. But in the minimal vimrc `c$` from cursor mode doesn't work either. It must depend on some vim setting, I'll look for the cause.

**Comment by mg979** [comment] 2018-12-08 11:02
There was a bug. It should be fixed in the test branch. Please notice that I also removed most mappings options there. Default mappings are now what they were in terminal vim (no mappings with meta keys by default).

**Closed** 2018-12-20 23:35 UTC
Labels: bug
