### ISSUE TITLE
multi-line can cause an infinite loop with 100% CPU usage

### ISSUE THREAD

**Issue by 3v1n0** [mg979/vim-visual-multi#89] opened 2019-10-23 16:53 UTC
I'm currently in this situation, I reproduced it various ways...

![immagine](https://user-images.githubusercontent.com/345675/67415945-3bf8c680-f5c6-11e9-98c3-42ded5020e9b.png)

Basically, `C-Down` to go multi-line, then tab to select up to `$` and eventually `y` (status bar says "Yanked the content of 3 regions), hitting return there causes the CPU to spin and my VIM to be freezing.

**Comment by mg979** [comment] 2019-10-23 19:44
I cannot reproduce it.

I tried`$<C-Down><C-Down><Tab>y`, then `return`

and also 

`<C-Down><C-Down><Tab>y`, then`return`

> hitting return

You wouln't need to hit `return` to yank things, anyway `return` isn't mapped by VM and shouldn't do anything, is your `<CR>` mapped to something in normal mode that could cause a loop?

**Comment by mg979** [comment] 2019-10-23 19:46
Also, can you provide vim version/OS? Thanks

**Comment by 3v1n0** [comment] 2019-10-24 03:27
> Also, can you provide vim version/OS? Thanks

Neovim, v0.3.8.

Effectively in normal mode my `Enter` key is mapped to `nnoremap <Enter> i<Enter>`

**Comment by mg979** [comment] 2019-11-16 03:16
Caused by the use of `feedkeys()` to start insert mode, replacing it with`startinsert` currently causes other issues, so it's still happening.

**Comment by mg979** [comment] 2019-12-17 05:22
Fixed via cc1921a

**Closed by mg979** 2019-12-17 05:22 UTC
Labels: bug
