### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by daniele-orlando** [mg979/vim-visual-multi#24] opened 2018-10-02 23:11 UTC
OS: MacOS 10.14
Vim: MacVIM

Reproduced on branch `test` (5a4a9ec0837153594dcb8432cd5ed35967176937) and branch `master` (a1969ece04193848579f87e9b6c9e6bdd404c406)

During the editor start, I receive this error:

```
Error detected while processing function vm#themes#init:
line   10:
E121: Undefined variable: g:VM_highlight_matches
E116: Invalid arguments for function empty(g:VM_highlight_matches)
E15: Invalid expression: !empty(g:VM_highlight_matches)
line   32:
E121: Undefined variable: g:VM
line   33:
E121: Undefined variable: g:VM
line   34:
E121: Undefined variable: g:VM
line   35:
E121: Undefined variable: g:VM 
```

I **CAN'T** reproduce the error on `vim` and `neovim`.

**Comment by mg979** [comment] 2018-10-02 23:18
Thanks for the report, do you get it on start? I'm fixing it now.

**Comment by daniele-orlando** [comment] 2018-10-02 23:27
Yes, during boot, but only with MacVIM. No problem with `vim` and `neovim`.

**Comment by mg979** [comment] 2018-10-02 23:32
Could you try now (test branch)? I could not reproduce it in terminal vim/nvim (Linux), but I moved the variable check so it should work.

**Comment by mg979** [comment] 2018-10-02 23:34
And btw, that variable controls matches highlight [styling](https://github.com/mg979/vim-visual-multi/wiki/H.-Highlight-colors#matches-highlight).

**Comment by daniele-orlando** [comment] 2018-10-02 23:35
Tested. It solved the ```E121: Undefined variable: g:VM_highlight_matches```.

Me too, I can only reproduce on MacVIM. vim/neovim work fine.

But
```
line   32:
E121: Undefined variable: g:VM
line   33:
E121: Undefined variable: g:VM
line   34:
E121: Undefined variable: g:VM
line   35:
E121: Undefined variable: g:VM 
```
persists.

**Comment by mg979** [comment] 2018-10-02 23:41
Can you try again? It must be triggered by a colorscheme loading before VimEnter event. Maybe you have that in your macvim-specific vimrc, but it's a bug nonetheless.

**Comment by daniele-orlando** [comment] 2018-10-02 23:51
Latest commit seams to fix the problem.

For completeness my .vimrc includes this block of code:
```
syntax on
filetype on
colorscheme janah-custom
```

**Comment by mg979** [comment] 2018-10-02 23:55
It was trying to initialize the theme before VM initialization, strange that it was ok on master because I can't see much changed in that department, but it should be fixed now.

**Comment by daniele-orlando** [comment] 2018-10-02 23:57
It was broken on `master` too.

**Comment by daniele-orlando** [comment] 2018-10-02 23:58
For reporting, these are the scripts executed by MacVIM:

```
 1: ~/Applications/MacVim.app/Contents/Resources/vim/vimrc
  2: ~/.vimrc
  3: ~/Storage/Sistemi/MacOS/user/lib/vim.conf/vimrc/plugins.vim
  4: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/ftoff.vim
  5: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-plug/plug.vim
  6: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
  7: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-javascript/ftdetect/javascript.vim
  8: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-vue/ftdetect/vue.vim
  9: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gradle/ftdetect/gradle.vim
 10: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-graphql/ftdetect/graphql.vim
 11: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/ftdetect/stylus.vim
 12: ~/Storage/Sistemi/MacOS/user/lib/vim.conf/after/ftdetect/tpl.vim
 13: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/menu.vim
 14: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/autoload/paste.vim
 15: ~/Storage/Sistemi/MacOS/user/lib/vim.conf/after/filetype.vim
 16: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/ftplugin.vim
 17: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/indent.vim
 18: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/syntax.vim
 19: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim
 20: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/syncolor.vim
 21: ~/Storage/Sistemi/MacOS/user/lib/vim.conf/vimrc/settings.vim
 22: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/macros/matchit.vim
 23: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 24: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/nosyntax.vim
 25: ~/Storage/Sistemi/MacOS/user/lib/vim.conf/after/colors/dan.vim
 26: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-janah/colors/janah.vim
 27: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-visual-multi/plugin/visual-multi.vim
 28: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-misc/plugin/xolox/misc.vim
 29: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-surround/plugin/surround.vim
 30: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/emmet-vim/plugin/emmet.vim
 31: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/editorconfig-vim/plugin/editorconfig.vim
 32: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-graphql/plugin/graphql.vim
 33: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-animatable-props.vim
 34: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-at-rules.vim
 35: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-colors.vim
 36: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-media-features.vim
 37: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-multi-props.vim
 38: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-props.vim
 39: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-pseudo.vim
 40: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-single-props.vim
 41: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-units.vim
 42: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/css-values.vim
 43: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/html-elements.vim
 44: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-stylus/plugin/svg-props.vim
 45: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/plugin/airline.vim
 46: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/init.vim
 47: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/parts.vim
 48: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/util.vim
 49: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline-themes/plugin/airline-themes.vim
 50: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-signature/plugin/signature.vim
 51: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-signature/autoload/signature/utils.vim
 52: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/plugin/gitgutter.vim
 53: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter/utility.vim
 54: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter/highlight.vim
 55: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
 56: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
 57: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
 58: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/manpager.vim
 59: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
 60: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
 61: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
 62: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
 63: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
 64: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
 65: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
 66: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
 67: ~/Storage/Sistemi/MacOS/user/lib/vim.conf/after/plugin/my.vim
 68: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-signature/after/plugin/signature.vim
 69: ~/Applications/MacVim.app/Contents/Resources/vim/gvimrc
 70: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-visual-multi/autoload/vm/themes.vim
 71: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions.vim
 72: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
 73: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline.vim
 74: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/netrw.vim
 75: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/term.vim
 76: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/undotree.vim
 77: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/hunks.vim
 78: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
 79: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
 80: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/keymap.vim
 81: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/section.vim
 82: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/highlighter.vim
 83: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline-themes/autoload/airline/themes/bubblegum.vim
 84: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/themes.vim
 85: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/builder.vim
 86: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-airline/autoload/airline/extensions/default.vim
 87: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/autoload/dist/ft.vim
 88: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/ftplugin/sql.vim
 89: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/autoload/sqlcomplete.vim
 90: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/autoload/syntaxcomplete.vim
 91: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/indent/sql.vim
 92: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/indent/sqlanywhere.vim
 93: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/sql.vim
 94: ~/Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/sqloracle.vim
 95: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-signature/autoload/signature/sign.vim
 96: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-signature/autoload/signature/mark.vim
 97: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter.vim
 98: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter/async.vim
 99: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter/debug.vim
100: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter/diff.vim
101: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-visual-multi/autoload/vm/plugs.vim
102: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-visual-multi/autoload/vm/maps.vim
103: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-visual-multi/autoload/vm/maps/all.vim
104: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-visual-multi/autoload/vm/operators.vim
105: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter/hunk.vim
106: ~/Storage/Sistemi/MacOS/user/lib/vim.home/bundle/vim-gitgutter/autoload/gitgutter/sign.vim
```

**Comment by mg979** [comment] 2018-10-02 23:59
Ok, so can you confirm it's fixed now? It's clear now what the issue is (was?).

**Comment by daniele-orlando** [comment] 2018-10-03 00:04
Yes, I confirm it is closed by 1cacdac3bfd40eb97d0174d0c8f3b2367e7440a6.

**Comment by mg979** [comment] 2018-10-03 00:05
Ok thanks for reporting! I'll have to update master as well.

**Comment by daniele-orlando** [comment] 2018-10-03 00:14
Thank you very much!

**Comment by mg979** [comment] 2018-10-03 01:42
pushed on master too

**Closed by mg979** 2018-10-03 01:42 UTC
