### ISSUE TITLE
Breaks after re-sourcing vimrc

### ISSUE THREAD

**Issue by jonsmithers** [mg979/vim-visual-multi#54] opened 2019-03-25 02:57 UTC
This is a small thing, but if you run `:source $MYVIMRC`, vim-visual-multi stops working. `<C-n>` prints the following:

```
Error detected while processing function vm#commands#ctrld[1]..<SNR>101_init[10]..vm#init_buffer[80]..1[3]..4:                                                          
line   11:
E716: Key not present in Dictionary: motions + g:Vm.find_motions)
```

**Comment by mg979** [comment] 2019-03-25 03:24
It seems that sourcing your vimrc clears the g:Vm global variable or its contents, and the plugin file isn't sourced again. Not sure if there's something I can do for that. I'll try to reproduce, though.

**Comment by jonsmithers** [comment] 2019-03-25 17:13
Re-sourcing [plugin/visual-multi.vim](https://github.com/mg979/vim-visual-multi/blob/3becd178d3f4965220824725a78bbae256894935/plugin/visual-multi.vim#L19) clears and re-populates the map. However, the `find_motion` key only gets set inside `vm#plugs#buffer()`, which only gets called when [autoload/vim.vim](https://github.com/mg979/vim-visual-multi/blob/3becd178d3f4965220824725a78bbae256894935/autoload/vm.vim#L7) is sourced (I've linked the relevant line numbers).  I don't think autoload files get re-sourced after they've already loaded. That would explain why `g:Vm` is missing certain keys on subsequent sourcings.

**Comment by mg979** [comment] 2019-03-26 03:45
I still can't reproduce it (after resourcing my vimrc), in any branch, your vim version and plugin branch?

It seems the error happens here.

https://github.com/mg979/vim-visual-multi/blob/204e278d7557bcd1951a17651dbb03db270f4f10/autoload/vm/maps.vim#L74

Could you please try to change this file

https://github.com/mg979/vim-visual-multi/blob/204e278d7557bcd1951a17651dbb03db270f4f10/autoload/vm/plugs.vim#L39

and move the lines 41 and 42 just outside the function, 3 lines above? Thanks

**Comment by jonsmithers** [comment] 2019-03-26 18:17
The changes you describe didn't fix the issue. According to a bit of debugging with  `:echom` and `:messages`, the issue is that `:source $MYVIMRC` causes `plugin/visual-multi.vim` to re-source, but it does _not_ cause `autoload/plugs.vim` to re-source.

So I tried installing `vim-visual-multi` as a native plugin instead of as a vim-plug plugin, and the issue went away. It seems like nothing in the plugin gets re-sourced when it's installed as a native plugin. But with vim-plug, just `plugin/visual-multi.vim` gets re-sourced.

I never imagined that plugin managers could exhibit different behaviors.

(FYI I'm using the `master` branch with Vim version 8.1)

**Comment by mg979** [comment] 2019-03-26 19:21
Ok I'm using vim-plug, but not for VM (it's in my `pack` folder). The problem is surely that the plugin is re-sourced, so the global var is reinitialized, but autoload scripts won't be sourced again, this happens in master because I didn't put a guard like

```vim
if exists('g:loaded_visual_multi')
  finish
endif
```

as it should be done in the plugin script. It's already fixed in the devel branch (if this is the reason it should work there). You could try the devel branch to be sure, then switch back to master, if you prefer master.

**Comment by jonsmithers** [comment] 2019-03-26 22:53
I can confirm it works on the devel branch. Maybe I'll stick with that for a while. Thanks for figuring this out!

**Comment by mg979** [comment] 2019-03-27 07:34
My bad for not putting a guard from the beginning, sorry for the issue and thanks for reporting. I'll leave this open until I merge devel on master.

**Comment by voldikss** [comment] 2019-03-27 11:34
Just ran into this trouble...
Also, thanks for figuring this out.

**Comment by mg979** [comment] 2019-04-10 16:41
Fixed in current master

**Closed by mg979** 2019-04-10 16:41 UTC
